channels:
- conda-forge
dependencies:
- ase =3.22.1
- lammps =2023.03.28
- mpich
- numpy =1.23.5
- pandas =1.5.3
- pathlib2 =2.3.7.post1
- pympipool =0.3.0
- scipy =1.10.1
- spglib =2.0.2
- sqsgenerator =0.2
