channels:
- conda-forge
dependencies:
- ase =3.22.1
- lammps =2023.03.28
- mpich
- numpy =1.23.5
- pandas =2.0.2
- pympipool =0.5.6
- pylammpsmpi =0.2.1
- scipy =1.10.1
- spglib =2.0.2
- sqsgenerator =0.2
