channels:
- conda-forge
dependencies:
- ase =3.22.1
- lammps =2023.03.28
- mpich
- numpy =1.23.5
- pandas =2.0.3
- pympipool =0.6.2
- pylammpsmpi =0.2.2
- scipy =1.11.1
- spglib =2.0.2
- sqsgenerator =0.2
- structuretoolkit =0.0.8
