channels:
- conda-forge
dependencies:
- ase =3.22.1
- coveralls
- coverage
- codacy-coverage
- lammps =2022.06.23
- numpy =1.24.2
- pandas =1.5.3
- pathlib2 =2.3.7.post1
- scipy =1.10.1
- spglib =2.0.2
- sqsgenerator =0.2
