# This runs jobs which pyiron modules should run on pushes or PRs to main

name: Actions tests and coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/tests-and-coverage.yml@main
    secrets: inherit
    with:
      tests-env-files: .ci_support/environment.yml ci_support/environment-abinit.yml .ci_support/environment-gpaw.yml .ci_support/environment-lammps.yml .ci_support/environment-qe.yml
    env:
      ABINIT_PP_PATH: '/usr/share/miniconda3/envs/my-env/share/abinit/LDA_FHI'
      ABI_PSPDIR: '/usr/share/miniconda3/envs/my-env/share/abinit/LDA_FHI'
      ASE_ABINIT_COMMAND: 'abinit PREFIX.in > PREFIX.log'
      ASE_ESPRESSO_COMMAND: "mpirun -np 1 pw.x -in PREFIX.pwi > PREFIX.pwo"
      ESPRESSO_PSEUDO: tests/static/qe
      OMPI_MCA_plm: isolated
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      OMPI_MCA_rmaps_base_oversubscribe: yes