# This workflow is used to test, if the code is compatible with jupyter notebooks providing usage examples

name: Notebooks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Merge Notebook environment
        run: |
          python .ci_support/condamerge.py .ci_support/environment.yml .ci_support/environment-notebooks.yml > environment.yml
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.11"
          miniforge-variant: Mambaforge
          channels: conda-forge
          channel-priority: strict
          activate-environment: my-env
          use-mamba: true
      - name: Update environment
        run: mamba env update -n my-env -f environment.yml
      - name: Setup
        shell: bash -l {0}
        run: |
          pip install --no-deps .
      - name: Test
        shell: bash -l {0}
        run: ./.ci_support/build_notebooks.sh