# This workflow is used to run the unittest of pyiron

name: OpenMPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
        - operating-system: macos-latest
          python-version: '3.11'
          label: osx-64-py-3-11
          prefix: /Users/runner/miniconda3/envs/my-env

        - operating-system: ubuntu-latest
          python-version: '3.11'
          label: linux-64-py-3-11
          prefix: /usr/share/miniconda3/envs/my-env

        - operating-system: windows-latest
          python-version: '3.11'
          label: win-64-py-3-11
          prefix: /usr/share/miniconda3/envs/my-env

        - operating-system: ubuntu-latest
          python-version: '3.10'
          label: linux-64-py-3-10
          prefix: /usr/share/miniconda3/envs/my-env

        - operating-system: ubuntu-latest
          python-version: '3.9'
          label: linux-64-py-3-9
          prefix: /usr/share/miniconda3/envs/my-env

        - operating-system: ubuntu-latest
          python-version: '3.8'
          label: linux-64-py-3-8
          prefix: /usr/share/miniconda3/envs/my-env

    steps:
    - uses: actions/checkout@v2
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        use-mamba: true
    - name: Update environment
      run: mamba env update -n my-env -f .ci_support/environment.yml
    - name: Setup
      shell: bash -l {0}
      run: |
        pip install --no-deps .
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 30
      run: coverage run --omit atomistics/_version.py -m unittest discover tests
    - name: Coverage
      if: matrix.label == 'linux-64-py-3-11'
      continue-on-error: True
      shell: bash -l {0}
      run: |
        coverage combine
        coveralls
        coverage xml
    - name: Codacy
      if: matrix.label == 'linux-64-py-3-11' && github.event_name != 'push'
      continue-on-error: True
      shell: bash -l {0}
      run: |
        python-codacy-coverage -r coverage.xml