# This workflow is used to run the unittest of pyiron

name: mpich

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
        - operating-system: macos-latest
          python-version: '3.11'
          label: osx-64-py-3-11
          prefix: /Users/runner/miniconda3/envs/my-env

        - operating-system: ubuntu-latest
          python-version: '3.11'
          label: linux-64-py-3-11
          prefix: /usr/share/miniconda3/envs/my-env

    steps:
    - uses: actions/checkout@v2
    - name: Setup environment
      run: cp .ci_support/environment-mpich.yml environment-mpich.yml
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        use-mamba: true
    - name: Update environment
      run: mamba env update -n my-env -f environment-mpich.yml
    - name: Setup
      shell: bash -l {0}
      run: |
        pip install --no-deps .
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 30
      run: for f in $(ls tests/*.py); do echo $f; python $f; done
